name: CI-CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Make Maven wrapper executable
        working-directory: order
        run: chmod +x mvnw

      - name: Build project
        working-directory: order
        run: ./mvnw clean package

      - name: Run tests
        working-directory: order
        run: ./mvnw test

      - name: Build Docker image
        working-directory: order
        run: docker build -t order-service .
