name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build project
        run: ./mvnw clean package

      - name: Run tests
        run: ./mvnw test

      - name: Build Docker image
        run: docker build -t order-service .